### ISSUE TITLE
Reverse bibliographic references?

### ISSUE THREAD

**Issue by a3nm** [pdm-book/community#1]
Hi,

Would it be possible to have a version of the book where the entries in the bibliography have backlinks to the places where they are cited? e.g., with `\usepackage[backref=true]{biblatex}`. I wanted to see where a given reference was used, but could not find it.

By the way, minor comment: there is an extra '.' in reference [3].

Thanks for your work on the book!

**Comment by pdm-book** [comment]
Thanks for the comments!

We have implemented your suggestion about having entries in the bibliography with backlinks (using package biblatex). You will see the changes in the next release of the book.

And we corrected the typo in reference [3].

Best!

Marcelo

**Comment by a3nm** [comment]
Great, thanks! Looking forward to an updated version of the PDF.

**Comment by a3nm** [comment]
This is apparently done now, thanks!
