### ISSUE TITLE
Definition 39.7: Eval(\varphi, \mathcal{I}, \eta) - missing \forall case

### ISSUE THREAD

**Issue by bscarone** [pdm-book/community#5]
Last bullet in the definition is a duplicate of the existential quantifier, it should probably be replaced by the universal one, switching the 'or' by an 'and' in the definition.

**Comment by marceloarenassaavedra** [comment]
Thanks for the comment, you are right about this typo. We corrected in the book, so this definition will be fine in its next version.

Best!
